apiVersion: v2
type: application

name: products
description: Paye Ton Kawa Products Management API
version: 0.1.0
appVersion: "0.1.0"
sources:
  - https://github.com/PayeTonKawa-EPSI-2025/Products-V2
