apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orders.fullname" . }}
  labels:
    {{- include "orders.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_DSN: {{ .Values.database.dsn | quote }}
  RABBIT_DSN: {{ .Values.rabbitmq.dsn | quote }}
